# Generated by Django 3.0.7 on 2020-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200815_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='gender',
            new_name='Criticality',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='gender',
            new_name='Criticality',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='applyp',
            name='gender',
        ),
        migrations.AddField(
            model_name='apply',
            name='Criticality',
            field=models.CharField(choices=[('M', 'Moderate'), ('S', 'Severe'), ('U', 'Urgent')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='applyp',
            name='Criticality',
            field=models.CharField(choices=[('M', 'Moderate'), ('S', 'Severe'), ('U', 'Urgent')], max_length=128, null=True),
        ),
    ]
