# Generated by Django 3.0.7 on 2020-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_candidate_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='gender',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Criticality',
            field=models.CharField(choices=[('M', 'Moderate'), ('S', 'Severe'), ('U', 'Urgent')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Description',
            field=models.CharField(choices=[('M', 'Moderate'), ('S', 'Severe'), ('U', 'Urgent')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Requirements',
            field=models.CharField(choices=[('M', 'Moderate'), ('S', 'Severe'), ('U', 'Urgent')], max_length=128, null=True),
        ),
    ]
