# Generated by Django 3.0.7 on 2020-09-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200919_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='last_company',
            new_name='Additional_info',
        ),
    ]
