# Generated by Django 3.0.7 on 2020-09-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200919_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Aadhar_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='PAN_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_salary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone_no',
        ),
    ]
